.github/workflows/ansible-test.yml, .gitignore, playbooks/microshift_image_build.yml, roles/image_builder/README.md, roles/image_builder/defaults/main.yml, roles/image_builder/handlers/main.yml, roles/image_builder/meta/main.yml, roles/image_builder/tasks/main.yml, roles/image_builder/tests/inventory, roles/image_builder/tests/test.yml, roles/image_builder/vars/main.yml
- added role to create microshift image
- added ini to gitignore
- created playbook for image role
```paste below
```
=> create microshift image

README.md
Signed-off-by: Adam Miller <admiller@redhat.com>
update README with some basic info
=> update README with some basic info

roles/image_builder/tasks/main.yml
change compose_type to builder_compose_type to pass the value to osbuild builder role.
```paste below
```
=> change compose_type to builder_compose_type

roles/image_builder/README.md, roles/image_builder/defaults/main.yml, roles/image_builder/tasks/main.yml, roles/image_builder/templates/firewall_options.j2
- Added default firewall option for mandatory microshift rules
- Added ability to create additional port/sources for zones
```paste below
```
=> added firewall config for microshift

roles/image_builder/README.md, roles/image_builder/tasks/main.yml, roles/image_builder/templates/lvms_setup.j2, roles/image_builder/vars/main.yml
Add storage config to kickstart file
```paste below
```
=> Add storage config to kickstart file

roles/image_builder/vars/main.yml
Fix issue where iso fails to auto install
```paste below
```
=> Fix iso auto install

roles/image_builder/README.md, roles/image_builder/tasks/main.yml, roles/image_builder/vars/main.yml
Pass sshkey instead of the file path
Resolves issue #8 
```paste below
```
=> pass sshkey instead of the file path

roles/image_builder/README.md, roles/image_builder/templates/lvms_setup.j2, roles/image_builder/vars/main.yml
Update lvms namespace to match the collection's namespace
Resolves issue #9 
```paste below
```
=> Update lvms namespace to match the collection

roles/image_builder/README.md, roles/image_builder/tasks/main.yml, roles/image_builder/templates/pull_secret.j2, roles/image_builder/vars/main.yml
- Added ability to provide pull secrets to kickstart
```paste below
```
=> added ability to provide pull secrets to kickstart

roles/image_builder/tasks/main.yml, roles/image_builder/vars/main.yml
Create set_fact loop to set fact in a drier way
```paste below
```
=> Create set_fact loop

galaxy.yml
=> update galaxy.yml file

galaxy.yml
=> updated galaxy

galaxy.yml
=> used latest version for osbuild

galaxy.yml
=> removed dependencies

galaxy.yml
=> Why ee why

playbooks/microshift_deploy_demo_app.yml
add playbook to deploy demo app to microshift
=> add playbook to deploy demo app to microshift

changelogs/config.yaml, meta/runtime.yml, playbooks/microshift_deploy_demo_app.yml, roles/image_builder/tasks/main.yml, roles/image_builder/tests/test.yml, roles/image_builder/vars/main.yml
Fix all current lint issues
```paste below
```
=> Fix lint issues

roles/image_builder/vars/main.yml
Add rhsm repo var for rhocp & fast_datapath_for_rhel
```paste below
```
=> Add rhsm repo var for rhocp & fast_datapath_for_rhel

playbooks/microshift_rpm_install.yml, roles/rpm_install/README.md, roles/rpm_install/defaults/main.yml, roles/rpm_install/handlers/main.yml, roles/rpm_install/meta/main.yml, roles/rpm_install/tasks/main.yml, roles/rpm_install/tests/inventory, roles/rpm_install/tests/test.yml, roles/rpm_install/vars/main.yml
Add rpm_install role to automate the install for Microshift on rpm based systems
```paste below
```
=> Add rpm install role

.github/CODEOWNERS, .github/CODE_OF_CONDUCT.md, .github/workflows/ansible-test.yml, CODE_OF_CONDUCT.md, README.md
- added codeowners
- move code of conduct to match osbuild
- updated readme with supported ansible versions
```paste below
```
=> Codeowners

README.md
content readme updated
```paste below
```
=> content readme updated

changelogs/fragments/1-create-microshift-image.yaml, changelogs/fragments/10-fix-iso-auto-install.yaml, changelogs/fragments/11-pass-sshkey.yaml, changelogs/fragments/12-update-lvms-namespace.yaml, changelogs/fragments/14-rhsm-repo.yaml, changelogs/fragments/15-provide-pull-secrets-to-kickstart.yaml, changelogs/fragments/16-fix-kickstart-post-omit-issue.yaml, changelogs/fragments/17-create-set-fact-loop.yaml, changelogs/fragments/18-microshift-test-playbook.yaml, changelogs/fragments/19-update-galaxy-file.yaml, changelogs/fragments/2-updated-readme-with-basic-info.yaml, changelogs/fragments/24-used-latest-version-for-osbuild.yaml, changelogs/fragments/25-removed-dependencies.yaml, changelogs/fragments/26-updated-galaxy-dependencies.yaml, changelogs/fragments/27-add-playbook-to-deploy-demo-app-to-microshift.yaml, changelogs/fragments/28-fix-lint-issues.yaml, changelogs/fragments/29-changed-how-kickstart-post-is-used.yaml, changelogs/fragments/3-change-compose-type-to-builder-compose-type.yaml, changelogs/fragments/30-add-app-role-to-deploy-manifests-onto-microshift-systems.yaml, changelogs/fragments/31-add-rhsm-repo-var-for-rhocp-and-fast-datapath-for-rhel.yaml, changelogs/fragments/32-relocate-rhsm-repos-info-management-to-infra.osbuild.yaml, changelogs/fragments/35-add-rpm-install-role.yaml, changelogs/fragments/36-codeowners.yaml, changelogs/fragments/37-content-readme.yaml, changelogs/fragments/4-firewall-config.yaml, changelogs/fragments/6-inject-ovs-kub-crio-config-into-kickstart.yaml, changelogs/fragments/7-add-storage-config-to-kickstart.yaml
added fragments of previous PRs
```paste below
```
=> added fragments of previous PRs

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/1-create-microshift-image.yaml, changelogs/fragments/10-fix-iso-auto-install.yaml, changelogs/fragments/11-pass-sshkey.yaml, changelogs/fragments/12-update-lvms-namespace.yaml, changelogs/fragments/14-rhsm-repo.yaml, changelogs/fragments/15-provide-pull-secrets-to-kickstart.yaml, changelogs/fragments/16-fix-kickstart-post-omit-issue.yaml, changelogs/fragments/17-create-set-fact-loop.yaml, changelogs/fragments/18-microshift-test-playbook.yaml, changelogs/fragments/19-update-galaxy-file.yaml, changelogs/fragments/2-updated-readme-with-basic-info.yaml, changelogs/fragments/24-used-latest-version-for-osbuild.yaml, changelogs/fragments/25-removed-dependencies.yaml, changelogs/fragments/26-updated-galaxy-dependencies.yaml, changelogs/fragments/27-add-playbook-to-deploy-demo-app-to-microshift.yaml, changelogs/fragments/28-fix-lint-issues.yaml, changelogs/fragments/29-changed-how-kickstart-post-is-used.yaml, changelogs/fragments/3-change-compose-type-to-builder-compose-type.yaml, changelogs/fragments/30-add-app-role-to-deploy-manifests-onto-microshift-systems.yaml, changelogs/fragments/31-add-rhsm-repo-var-for-rhocp-and-fast-datapath-for-rhel.yaml, changelogs/fragments/32-relocate-rhsm-repos-info-management-to-infra.osbuild.yaml, changelogs/fragments/35-add-rpm-install-role.yaml, changelogs/fragments/36-codeowners.yaml, changelogs/fragments/37-content-readme.yaml, changelogs/fragments/4-firewall-config.yaml, changelogs/fragments/6-inject-ovs-kub-crio-config-into-kickstart.yaml, changelogs/fragments/7-add-storage-config-to-kickstart.yaml
=> create version changelog, first release tag

changelogs/fragments/40-remove-general-collection.yaml, galaxy.yml, requirements.yml
removed general collection from requirements.yml
```paste below
```
=> Remove general collection

.github/workflows/ansible-lint.yml, .github/workflows/ansible-test.yml, .github/workflows/extra-docs-linting.yml, changelogs/changelog.yaml, changelogs/fragments/41-ansible-lint-github-workflows.yaml, galaxy.yml, requirements.yml, roles/image_builder/tasks/main.yml
added ansible-lint to github workflows
```paste below
```
=> added ansible-lint to github workflows

.github/workflows/ansible-test.yml, changelogs/fragments/45-publish-trigger-github-workflow.yaml
add publish trigger for github workflow
```paste below
```
=> add publish trigger for github workflow

README.md
remove under devel notice
```paste below
```
=> remove under devel notice

changelogs/fragments/51-update-osbuild-from-git-to-galaxy.yaml, galaxy.yml, requirements.yml
Update osbuild from git to galaxy now that osbuild is on galaxy
```paste below
```
=> Update osbuild from git to galaxy

.github/pull_request_template.md, README.md, changelogs/fragments/52-update-new-repo-location.yaml, galaxy.yml, requirements.yml
=> Update to new repo location

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/41-ansible-lint-github-workflows.yaml, changelogs/fragments/45-publish-trigger-github-workflow.yaml, changelogs/fragments/46-replace-system-roles.yaml, changelogs/fragments/47-add-release-workflow.yaml, changelogs/fragments/48-fix-readme-&-galaxy.yaml, changelogs/fragments/49-delete-unsued-docs-dir.yaml, changelogs/fragments/51-update-osbuild-from-git-to-galaxy.yaml, changelogs/fragments/52-update-new-repo-location.yaml
2.0.1 release
FIXES: 
What is it?
=> 2.0.1 release

README.md, changelogs/fragments/54-release-1.0.2.yaml, galaxy.yml
release 1.0.2
FIXES: 
What is it?
=> release 1.0.2

changelogs/fragments/61-fix-pkg-bug-update-Microshift-to-4_13.yaml, roles/image_builder/defaults/main.yml, roles/image_builder/tasks/main.yml, roles/image_builder/vars/main.yml
Fix  builder_compose_pkgs bug
update Microshift to 4.13
FIXES: 
What is it?
=> Update Microshift to 4.13, fix pkg var bug

CHANGELOG.rst, README.md, build_context/_build/requirements.yml, changelogs/changelog.yaml, changelogs/fragments/54-release-1.0.2.yaml, changelogs/fragments/56-add-execution-environment.yaml, changelogs/fragments/57-add-defaults-to-all-ifs.yaml, changelogs/fragments/61-fix-pkg-bug-update-Microshift-to-4_13.yaml, galaxy.yml, requirements.yml
New release for 1.0.3
FIXES: 
What is it?
=> added changelogs for new release 1.0.3

changelogs/fragments/63-add-default-skip-lvms-in-kickstart-post.yaml, roles/image_builder/defaults/main.yml
Add default to skip lvms in kickstart post
What is it?
=> Add default to skip lvms in kickstart post

build_context/_build/requirements.yml, changelogs/fragments/64-fix-kickstart-post-to-match-convention.yaml, roles/image_builder/defaults/main.yml, roles/image_builder/tasks/main.yml
Fix kickstart post to match convention
FIXES: 
What is it?
=> Fix kickstart post to match convention
